export type { Character, Phase, ChildPreference, SoundType, SynthFunction, SVGGenerator } from './types'
export { NOTES, BPM, STEP_DURATION, TOTAL_STEPS } from './notes'
export { initAudio, destroyAudio, setMasterVolume, getAudioContext, getMasterGain } from './audio-context'
export { kick, snare, hihat, shaker, elec, lead, vibes, pad, sub, vocal, darkVocal, darkVocal2, glitch, whistle, robot, sonicKick, powerHit } from './synths'
export { sprunkiSVG, customSVG } from './svg-builders'
export { ALL_PHASES, getPhaseCharacters } from './characters'
export { BASE_PHASES, generateSurprisePhase } from './phases'
export { generateSurpriseCharacters, getAvailableThemes, isKnownTheme } from './character-generator'
export { buildGameSequence, buildDefaultSequence, calculateTotalPhases } from './surprise-engine'
export type { GamePhase } from './surprise-engine'
export { connectSequencer, startSequencer, stopSequencer, startIntegratedSequencer, resetSequencer, isSequencerPlaying, getCurrentStep, onStep } from './sequencer'
